version: '3.9'

services:
  postgres:
    # this is equivalent to Supabase’s postgres version
    image: postgres:15.1
    ports:
      - 5670:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
    driver: local
